set_cooloven:
  target:
    entity:
      - integration: panasonic_japan
  fields:
    mode:
      required: false
      example: quench
      selector:
        select:
          options:
            - off
            - quench
            - cold
            - frozen
    time:
      required: false
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1
    second:
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 50
          step: 10